{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fredr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fredr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fredr/fredr_{{ version }}.tar.gz
  sha256: 574654038eb353353a8c88d88f2a48ea7b588625a512c4201a37b8dc00c4e300

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-jsonlite
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-httr
    - r-jsonlite
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('fredr')"           # [not win]
    - "\"%R%\" -e \"library('fredr')\""  # [win]

about:
  home: https://github.com/sboysel/fredr
  license: MIT
  summary: An R client for the 'Federal Reserve Economic Data' ('FRED') API <https://research.stlouisfed.org/docs/api/>.  Functions
    to retrieve economic time series and other data from 'FRED'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: fredr
# Title: An R Client for the 'FRED' API
# Version: 2.1.0
# Authors@R: c(person(given = "Sam", family = "Boysel", role = c("aut", "cre"), email = "sboysel@gmail.com"), person(given = "Davis", family = "Vaughan", role = "aut", email = "davis@rstudio.com"))
# Maintainer: Sam Boysel <sboysel@gmail.com>
# Description: An R client for the 'Federal Reserve Economic Data' ('FRED') API <https://research.stlouisfed.org/docs/api/>.  Functions to retrieve economic time series and other data from 'FRED'.
# License: MIT + file LICENSE
# URL: https://github.com/sboysel/fredr
# BugReports: https://github.com/sboysel/fredr/issues
# Depends: R (>= 3.2.2)
# Imports: httr, jsonlite, rlang, tibble
# Suggests: covr, dplyr, ggplot2, knitr, purrr, rmarkdown, testthat, xts, zoo
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-01-29 14:39:34 UTC; davis
# Author: Sam Boysel [aut, cre], Davis Vaughan [aut]
# Repository: CRAN
# Date/Publication: 2021-01-29 18:10:02 UTC
